version: '3'

services:

  redis:
      image: redis
      container_name: redis-account-manager
      restart: always
      ports:
        - 6379:6379
      command: redis-server --requirepass 123@Mudar

  postgresdba-ccount-manage:
    container_name: account-manager
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: account-manager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123@Mudar
    ports:
      - 5433:5432

  postgresdb-transaction-pix:
    container_name: transaction-pix
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123@Mudar
    ports:
      - 5434:5432

  postgresdbBancoExemplo:
    container_name: banco-database
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: bancoTeste
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123@Mudar
    ports:
      - 5432:5432