version: '3.7'

services: 
  redis:
      image: redis
      container_name: redis-account-manager
      restart: always
      ports:
        - 6379:6379
      command: redis-server --requirepass 123@Mudar

  postgresdb:
    container_name: account-manager
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: account-manager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123@Mudar
    ports:
      - 5433:5432
    