version: '3.7'

services:  
  postgresdb:
    container_name: account-manager
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: account-manager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123@Mudar
    ports:
      - 5432:5432
    